### PR TITLE
Feat: auth signup and logout

### PR DESCRIPTION
**Pull request by ankit9015**
This PR has following features:
1. Signup and logout functionality added 
2. Page structure is updated
3. When user logins/signup a logout button is displayed in Navbar
4. Protected pages render only when the user is logged-in
5. The UI of webapp will be updated later

### CODE REVIEW

**Review by rushikesh3299 — APPROVED** [review]
Looks good to me. Just a suggestion please try to generate a bit small pr's

**Review by SaurabhChawda — APPROVED** [review]
Looks good to me, but you can improve design.

**Comment by ankit9015** [comment]
> Looks good to me. Just a suggestion please try to generate a bit small pr's

Yes, the actual PR is not that large but it is based on another Branch that was not merged with dev when this PR was raised

**Comment by ankit9015** [comment]
> Looks good to me, but you can improve design.

Yes, will update the UI later

**Pull request merged**
